language: python
python:
  - "2.7"
sudo: required

branches:
  only:
    - master

cache:
  - pip

install:
    #- git clone https://github.com/openstack/keystone.git -b stable/mitaka
    #- cd keystone
    #- pip install -r requirements.txt
    #- pip install -r test-requirements.txt
    #- pip 
    - sudo apt-get install keystone
    - pip install flake8 pytest python-novaclient python-neutronclient python-cinderclient

script:
  - py.test
  #- py.test --ignore=keystone
  - flake8

