language: python
python:
  - "2.7"
dist: trusty
sudo: required

branches:
  only:
    - master

cache:
  - pip

before_install: 
    - sudo apt-get purge mysql-client-core-5.6
    - sudo apt-get purge mysql-server-core-5.6
    - sudo apt-get remove mysql-client mysql-server
    - sudo apt-get remove mariadb*
    - sudo apt-get autoremove
    - sudo apt-get autoclean 
    #- sudo rm /var/lib/mysql/debian-5.6.flag
    #- sudo apt-get install mysql-client-core-5.5
    #- sudo apt-get install mysql-server-core-5.5 
    #- sudo apt-get install mysql-server
    #- sudo apt-get install mysql-client-5.5

install:
    - sudo useradd -d /opt/stack -m -s /bin/bash stack
    - sudo cp local.conf /opt/stack/
    - sudo chown stack:stack /opt/stack/local.conf
    - echo 'stack ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers
    - sudo su - stack -c "git clone https://git.openstack.org/openstack-dev/devstack -b stable/mitaka; cp local.conf devstack ; cd devstack ; ./stack.sh;"
    - pip install flake8 pytest python-novaclient python-neutronclient python-cinderclient

script:
  - py.test
  - flake8

