language: python
python:
  - "2.7"
sudo: required

branches:
  only:
    - master

cache:
  - pip

install:
    - pip install flake8 pytest python-novaclient python-neutronclient python-cinderclient
    - git clone https://github.com/openstack-dev/devstack.git -b stable/mitaka
    - cd devstack
    - ./stack.sh

script:
  - py.test
  - flake8

