language: python
python:
  - "2.7"
dist: trusty
sudo: required

branches:
  only:
    - master

cache:
  - pip

install:
    - pip install flake8 pytest python-novaclient python-neutronclient python-cinderclient
    - sudo useradd -d /opt/stack -m -s /bin/bash stack
    - echo 'stack ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers
    - sudo su - stack -c "git clone https://git.openstack.org/openstack-dev/devstack -b stable/mitaka ; cd devstack ; ./stack.sh"

script:
  - py.test
  - flake8

